# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a591204975bf5d76a6580724ea073ba085333b0dfe9e61947cae1b44b53568bc875863e750860619ca3a65e2d6735b9c55869d1f731165afe62762ee47af605

test:
  secret_key_base: 1b4417a5dbc3037ac411badb509db350ee2adbfe483290b3c9a1c0875d3ed60ef30c353c6057f6909c90e3b5fb640176435ae7b9c5be9ba06495f104c2efda37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
